# Generated by Django 5.0.4 on 2024-05-06 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0006_alter_customuser_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavereportstudent",
            name="student_id",
        ),
        migrations.DeleteModel(
            name="LeaveReportStaff",
        ),
        migrations.DeleteModel(
            name="LeaveReportStudent",
        ),
    ]
